knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration

        google:
            type: google
            client_id: '%env(resolve:OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(resolve:OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: app_oauth_check
            redirect_params:
                provider: google

        github_fr:
            type: github
            client_id: '%env(resolve:OAUTH_GITHUB_FR_CLIENT_ID)%'
            client_secret: '%env(resolve:OAUTH_GITHUB_FR_CLIENT_SECRET)%'
            redirect_route: app_oauth_check
            redirect_params:
                provider: github

        github_en:
            type: github
            client_id: '%env(resolve:OAUTH_GITHUB_EN_CLIENT_ID)%'
            client_secret: '%env(resolve:OAUTH_GITHUB_EN_CLIENT_SECRET)%'
            redirect_route: app_oauth_check
            redirect_params:
                provider: github

        github_ko:
            type: github
            client_id: '%env(resolve:OAUTH_GITHUB_KO_CLIENT_ID)%'
            client_secret: '%env(resolve:OAUTH_GITHUB_KO_CLIENT_SECRET)%'
            redirect_route: app_oauth_check
            redirect_params:
                provider: github